services:
  mysql:
    image: bitnami/mysql
    volumes:
      - ./db:/bitnami/mysql/data
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=staart
      - MYSQL_PASSWORD=staart
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=node-application-database

volumes:
  db:
